version: '3.9'

services:
  web:
    build:
      context: .
      args:
        APP_PATH: ${APP_PATH}
        RAILS_PORT: ${RAILS_PORT}
    depends_on:
      - postgres
    command:
      - /bin/sh
      - -c
      - |
        bundle exec rake db:migrate
        bundle exec rails s -p ${RAILS_PORT} -b ${RAILS_BIND}
    env_file:
      - '.env'
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    volumes:
      - .:${APP_PATH}
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${COMIC_APP_DATABASE_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
